var fa=new (function(){var e=this,H=false,B=0,R=0;this.getTime=function(b){return b=="g"?B+R:B};var S=0,T=0,U=0;this.X=function(){return T};this.Y=function(){return U};var C=50;this.Fa=function(b){C=1E3/parseInt(b);return e};this.la=function(){return 1E3/C};this.ma=function(){return S};var y="sprites/";this.Ga=function(b){y=b;return e};this.na=function(){return y};var I=false,V=0,J=0;this.Ja=function(b,a){I=true;V=b;J=a;return e};this.Ia=function(){I=false;J=V=0;return e};var F=false,D=[["bsp",8],
["tab",9],["ent",13],["shf",16],["ctr",17],["alt",18],["pau",19],["cap",20],["esc",27],["sp",32],["pgu",33],["pgd",34],["end",35],["hom",36],["la",37],["ua",38],["ra",39],["da",40],["ins",45],["del",46],["d0",48],["d1",49],["d2",50],["d3",51],["d4",52],["d5",53],["d6",54],["d7",55],["d8",56],["d9",57],["sem",59],["eql",61],["a",65],["b",66],["c",67],["d",68],["e",69],["f",70],["g",71],["h",72],["i",73],["j",74],["k",75],["l",76],["m",77],["n",78],["o",79],["p",80],["q",81],["r",82],["s",83],["t",
84],["u",85],["v",86],["w",67],["x",88],["y",89],["z",90],["lwn",91],["rwn",92],["sel",93],["n0",96],["n1",97],["n2",98],["n3",99],["n4",100],["n5",101],["n6",102],["n7",103],["n8",104],["n9",105],["mul",106],["add",107],["sub",109],["dec",110],["div",111],["f1",112],["f2",113],["f3",114],["f4",115],["f5",116],["f6",117],["f7",118],["f8",119],["f9",120],["f10",121],["f11",122],["f12",123],["num",144],["scr",145],["com",188],["per",190],["fsl",191],["acc",192],["obr",219],["bsl",220],["cbr",221],["qot",
222]];function W(b,a){for(var d=D.length,i=0;i<d;i++)if(D[i][1]==b)D[i][2]=a}function X(b){W((b?b:window.event).keyCode,true);F=true}function Y(b){W((b?b:window.event).keyCode,false);F=true}this.key=function(b){for(var a=D.length,d=0;d<a;d++)if(D[d][0]==b)return D[d][2]?true:false};var N=0,O=0,G=false;this.o=new function(){this.x=function(){return N};this.y=function(){return O};this.K=function(){return G}};function $(b){if(!b)b=window.event;if(b.offsetX){N=b.offsetX;O=b.offsetY}else{N=b.layerX;O=
b.layerY}}G=function(){G=true};function aa(){G=false}function P(b,a,d){d=d*0.0174532925;b=[b[0]-a[0],b[1]-a[1]];b=[b[0]*Math.cos(d)-b[1]*Math.sin(d),b[0]*Math.sin(d)+b[1]*Math.cos(d)];b[0]+=a[0];b[1]+=a[1];return b}this.b=[];this.m=function(b,a,d,i,s,j){this.m="";this.name=b;this.r=a;this.u=d;this.q=i;this.width=s;this.height=j;this.p=this.e=this.f=0;this.ya=function(){return this.f};this.za=function(){return this.e};this.B=function(){return this.f+this.width};this.C=function(){return this.e+this.height};
this.s=this.k=this.j=0;this.l=this.d=false;this.display=function(f,c,h,g){this.u=f;this.f=c;this.e=h;this.p=g?g:h;this.d=true;if(f!==""){this.l=true;c=document.createElement("div");c.id="ent_"+this.name;c.style.width=this.width;c.style.height=this.height;if(f!=" "){c.style.backgroundImage="url('"+y+this.r+"/"+f+"."+this.q+"')";c.style.backgroundRepeat="no-repeat"}c.style.position="absolute";c.style.left=this.f+"px";c.style.top=this.e+"px";document.getElementById("board").appendChild(c);if(this.g.length>
0)for(f=0;f<this.g.length;f++)u(this,this.g[f])}else this.l=false;return this};this.M=function(){if(document.getElementById("ent_"+this.name)){var f=document.getElementById("ent_"+this.name);f.parentNode.removeChild(f)}this.l=this.d=false;return this};this.ga=function(f){this.u=f;var c=document.getElementById("ent_"+this.name);if(c)if(f!=""){this.l=true;c.style.backgroundImage="url('"+y+this.r+"/"+f+"."+this.q+"')"}else{c.parentNode.removeChild(c);this.l=false}else if(f!="")this.display(f,this.f,
this.e,this.f);else this.l=false;return this};this.R=function(f,c){var h=document.getElementById("ent_"+this.name);if(h)h.style.background="url('"+y+this.r+"/"+this.u+"."+this.q+"') "+f+"px "+c+"px no-repeat"};this.w={};this.$=function(f,c,h){this.w[f]=[c,h];return this};this.Ha=function(f){f in this.w&&this.R(this.w[f][0],this.w[f][1]);return this};this.move=function(f,c,h){this.j+=f;this.k+=c;this.s+=h?h:c;return this};this.ia=function(){return[this.j,this.k,this.s]};this.V=function(f){if(f)if(f==
"x")this.j=0;else if(f=="y")this.k=0;else{if(f=="z")this.s=0}else this.s=this.k=this.j=0;return this};this.moveTo=function(f,c,h){this.f=f;this.e=c;this.p=h||h==0?h:c;return this};this.rotate=function(f){var c=document.getElementById("ent_"+this.name);if(c)c.style[e.D.I]="rotate("+f+"deg)";return this};this.Da=function(f,c){var h=[this.width/2,this.height/2],g=[f[0],f[1]],n=P([f[2],f[3]],h,c),o=P([f[4],f[5]],h,c);h=P([f[6],f[7]],h,c);g.push(n[0]);g.push(n[1]);g.push(o[0]);g.push(o[1]);g.push(h[0]);
g.push(h[1]);return g};this.oa=function(){return I?Math.floor(this.e/J):false};this.pa=function(){return I?Math.floor(this.e/J):false};this.ha=function(){if(e.o.K())if(e.o.x()>this.f&&e.o.x()<this.B())if(e.o.y()>this.e&&e.o.y()<this.C())return true;return false};this.da=function(f){var c=document.getElementById("ent_"+this.name);c&&c.appendChild(f);return this};this.detach=function(){var f=document.getElementById("ent_"+this.name);if(f)for(var c=f.childNodes.length,h=0;h<c;h++)f.removeChild(f.childNodes[0]);
return this};this.g=[];this.Z=function(f,c,h,g,n,o,l,k,m){this.g.push([f,c,h,g,n,o,l,k?k:0,m?m:0]);document.getElementById("ent_"+this.name)&&u(this,this.g[this.g.length-1]);return this};function q(f,c){if(typeof c=="number")var h=f.g[c];else for(var g=0;g<f.g.length;g++)if(f.g[g][0]==c){h=f.g[g];break}if(h)return h;return false}function u(f,c){var h=document.getElementById("ent_"+f.name+"_"+c[0]);if(h){h.style.left=c[2]+"px";h.style.top=c[3]+"px";h.style.zIndex=c[4];h.style.width=c[5]+"px";h.style.height=
c[6]+"px";h.style.background='url("'+y+f.r+"/"+c[1]+"."+f.q+'") no-repeat '+c[7]+"px "+c[8]+"px"}else{var g=document.getElementById("ent_"+f.name);if(g){h=document.createElement("div");h.id="ent_"+f.name+"_"+c[0];h.style.position="absolute";h.style.left=c[2]+"px";h.style.top=c[3]+"px";h.style.zIndex=c[4];h.style.width=c[5]+"px";h.style.height=c[6]+"px";h.style.overflow="hidden";if(c[1]!=" ")h.style.background='url("'+y+f.r+"/"+c[1]+"."+f.q+'") no-repeat '+c[7]+"px "+c[8]+"px";g.appendChild(h)}}}this.sa=
function(f,c,h,g){if(f=q(this,f)){f[2]=c;f[3]=h;f[4]=g;u(this,f)}return this};this.Ba=function(f,c,h){if(f=q(this,f)){f[5]=c;f[6]=h;u(this,f)}return this};this.ea=function(f,c,h,g){if(f=q(this,f)){f[1]=c;f[7]=h||h===0?h:f[7];f[8]=g||g===0?g:f[8];u(this,f)}return this};this.removeChild=function(f){if(typeof f=="number")var c=f;else for(var h=0;h<this.g.length;h++)if(this.g[h][0]==f){c=h;break}if(c||c==0){f=document.getElementById("ent_"+this.name+"_"+this.g[c][0]);f.parentNode.removeChild(f);this.g.slice(c,
1)}return this};this.back=function(){return this.m};this.end=function(){return e}};this.ta=function(b){b.a.m=b;e.b[e.b.length]=b;b.F&&b.F();return b};this.P=function(b){e.b.splice(b,1);return e};this.h={};this.map=function(b,a,d,i,s){this.name=b;this.path=a;this.L=d;this.d=false;this.width=i;this.height=s;this.y=this.x=0;this.t=-1;this.move=function(j,q,u){this.x+=j;this.y+=q;if(u)this.t+=u;if(document.getElementById("map_"+this.name)){j=document.getElementById("map_"+this.name);j.style.marginLeft=
this.x+"px";j.style.marginTop=this.y+"px";j.style.zIndex=this.t}return this};this.moveTo=function(j,q,u){this.x=j;this.y=q;if(u)this.t=u;if(document.getElementById("map_"+this.name)){j=document.getElementById("map_"+this.name);j.style.marginLeft=this.x+"px";j.style.marginTop=this.y+"px";j.style.zIndex=this.t}return this};this.display=function(){this.d=true;if(document.getElementById("map_"+this.name))document.getElementById("map_"+this.name).style.display="block";else{var j=document.createElement("div");
j.id="map_"+this.name;j.style.backgroundImage="url('"+y+"maps/"+this.path+"."+this.L+"')";j.style.width=this.width+"px";j.style.height=this.height+"px";j.style.position="absolute";j.style.overflow="hidden";j.style.marginLeft=this.x+"px";j.style.marginTop=this.y+"px";j.style.zIndex=this.t;document.getElementById("board").appendChild(j)}return this};this.M=function(){this.d=false;if(document.getElementById("map_"+this.name))document.getElementById("map_"+this.name).style.display="none";return this};
this.remove=function(){this.d=false;if(document.getElementById("map_"+this.name)){var j=document.getElementById("map_"+this.name);j.parentNode.removeChild(j)}return this};this.end=function(){return e}};this.ua=function(b,a,d,i,s){e.h[b]=new e.map(b,a,d,i,s);return e.h[b]};this.Aa=function(b){e.h[b]&&delete e.h[b];return e};this.rules={};this.c=[[],[],[],[]];this.v=function(b,a){this.d=b;this.G=a};this.va=function(b,a){e.rules[b]=a;e.c[a.a.G].push(b);return e};this.removeRule=function(b){if(e.rules[b]){for(var a=
e.c[e.rules[b].a.G],d=0,i=a.length;d<i;d++)if(a[d]==b){a.splice(d,1);break}delete e.rules[b]}return e};var x={};function z(b){var a=b instanceof Array?[]:{};for(prop in b)a[prop]=prop=="ent"?"":b[prop]&&typeof b[prop]=="object"?z(b[prop],a):b[prop];return a}this.Ea=function(b){x[b]={b:z(e.b,e),h:z(e.h,e),rules:z(e.rules,e),c:z(e.c,e)};for(var a=x[b].b.length,d=0;d<a;d++)x[b].b[d].a.m=x[b].b[d];return e};this.qa=function(b){if(x[b])return true;return false};this.ra=function(b){if(x[b]){e.b=z(x[b].b,
b);e.h=z(x[b].h,b);e.rules=z(x[b].rules,b);e.c=z(x[b].c,b);for(map in e.h)e.h[map].d==true&&e.h[map].display();b=e.b.length;for(var a=0;a<b;a++){e.b[a].a.m=e.b[a];e.b[a].a.d==true&&e.b[a].a.display(e.b[a].a.u,e.b[a].a.f,e.b[a].a.e,e.b[a].a.p)}F=true}return e};this.Ca=function(b){x[b]&&delete x[b];return e};var K=null;this.ca=function(b){K=b;return e};var L=null;this.ba=function(b){L=b;return e};this.aa=function(b,a){var d=new XMLHttpRequest;d.open("GET",b,true);d.overrideMimeType("application/json");
d.onreadystatechange=function(){if(d.readyState==4){eval("("+d.responseText+")");eval(a+"(resp)")}};d.send(null);return e};this.ka=function(){return e};this.H={};this.i=[];this.xa=function(b){var a=e.i.length;e.i[a]=document.createElement("audio");e.i[a].src=e.H[b].src;e.i[a].play();return e};this.wa=function(b,a){e.H[b]=new Audio(a);return e};var M=[];this.Ka=function(b,a,d){for(var i=d.length,s=0;s<i;s++){M[M.length]=new Image;M[M.length-1].src=y+b+"/"+d[s]+"."+a}return e};this.fa=function(b){document.getElementById("board").style.cursor=
"url('"+y+b+"')";return e};this.D={J:function(){function b(){for(var a=document.getElementsByTagName("body")[0],d=["transform","WebkitTransform","MozTransform"],i;i=d.shift();)if(typeof a.style[i]!="undefined")return i;return false}this.I=b()?b():"none"},I:"none"};this.S=function(){for(var b=document.getElementById("board"),a=b.childNodes.length,d=0;d<a;d++)b.removeChild(b.childNodes[0]);return e};this.T=function(){e.b=[];return e};this.U=function(){e.h={};return e};this.W=function(){e.rules={};e.c=
[[],[],[],[]];return e};this.La=function(){e.S().T().U().W();return e};this.F=function(b,a,d){e.D.J();var i=document.createElement("div");i.id="board";T=b;U=a;i.style.width=b+"px";i.style.height=a+"px";i.style.overflow="hidden";i.style.position="relative";d?document.getElementById(d).appendChild(i):document.getElementsByTagName("body")[0].appendChild(i);if(window.document.addEventListener){window.document.addEventListener("keydown",X,false);window.document.addEventListener("keyup",Y,false)}else{window.document.attachEvent("onkeydown",
X);window.document.attachEvent("onkeyup",Y)}i.onmousemove=$;i.onmousedown=G;i.onmouseup=aa;return e};this.start=function(){if(H==false){H=true;B=setTimeout("rw.run()",C)}return e};this.stop=function(){H=false;return e};function Q(b,a,d,i){b=(d[0]-a[0])*(b[1]-a[1])-(d[1]-a[1])*(b[0]-a[0]);return(d[0]-a[0])*(i[1]-a[1])-(d[1]-a[1])*(i[0]-a[0])>=0?b>=0?true:false:b<=0?true:false}function v(b,a,d,i){return Q(b,a,d,i)?Q(b,d,i,a)?Q(b,i,a,d)?true:false:false:false}function A(b,a,d){if(b[0]<a[0])return false;
if(b[0]>d[0])return false;if(b[1]<a[1])return false;if(b[1]>d[1])return false;return true}function ba(b,a,d,i,s,j){var q=true;(b-i)*(b-i)+(a-s)*(a-s)<(d+j)*(d+j)?q=true:q=false;return q}function E(b,a,d){if(d[0]-d[2]>b[0]&&d[0]-d[2]>a[0])return false;else if(d[0]+d[2]<b[0]&&d[0]+d[2]<a[0])return false;else if(d[1]-d[2]>b[1]&&d[1]-d[2]>a[1])return false;else if(d[1]+d[2]<b[1]&&d[1]+d[2]<a[1])return false;else{var i=b[0]*a[1]+a[0]*d[1]+d[0]*b[1]-a[0]*b[1]-d[0]*a[1]-b[0]*d[1];if(i<0)i=-i;return d[2]>
i/Math.sqrt((a[0]-b[0])*(a[0]-b[0])+(a[1]-b[1])*(a[1]-b[1]))?true:false}}function Z(b,a,d,i,s,j,q){var u=true;j=(j-i)/2;b=b-(i+j);if(b<0)b=-b;if(b>j+d)u=false;else{q=(q-s)/2;a=a-(s+q);if(a<0)a=-a;u=a>q+d?false:b<=j?true:a<=q?true:(b+j)*(b+j)+(a+q)*(a+q)<=d*d?true:false}return u}this.Q=function(){for(var b=new Date,a=0;a<e.i.length;a++)if(e.i[a].ended){e.i.splice(a,1);a--}if(typeof K=="function"){K();K=null}a=0;for(var d=e.c[0].length;a<d;a++)e.rules[e.c[0][a]].a.d&&e.rules[e.c[0][a]].v();var i=[],
s=e.b.length;if(F==true){for(a=0;a<s;a++){d=e.b[a];if(d.a.d==true){d.N&&d.N();d=d.update(d.a.f,d.a.B(),d.a.e,d.a.C());d==false&&i.push(a)}else if(d.A){d=d.A();d==false&&i.push(a)}}F=false}else for(a=0;a<s;a++){d=e.b[a];if(d.a.d==true){d=d.update(d.a.f,d.a.B(),d.a.e,d.a.C());d==false&&i.push(a)}else if(d.A){d=d.A();d==false&&i.push(a)}}a=0;for(d=e.c[1].length;a<d;a++)e.rules[e.c[1][a]].a.d&&e.rules[e.c[1][a]].v();var j=[];for(a=0;a<s;a++){var q=e.b[a];if(q.a.d&&q.n)for(d=a+1;d<s;d++){var u=e.b[d];
if(u.a.d&&u.n)for(var f=0;f<q.n.length;f++)for(var c=q.n[f],h=0;h<u.n.length;h++){var g=u.n[h],n=false,o=c[1];if(o)for(var l=o.length,k=0;k<l;k++)if(o[k]==g[0])n=true;if(n){var m=q.a.f+q.a.j;l=q.a.e+q.a.k;o=u.a.f+u.a.j;n=u.a.e+u.a.k;k=true;if(c[7])if(g[7]){var p=[c[2]+m,c[3]+l],t=[c[4]+m,c[5]+l],r=[c[6]+m,c[7]+l];l=[g[2]+o,g[3]+n];m=[g[4]+o,g[5]+n];var w=[g[6]+o,g[7]+n];v(p,l,m,w)?k=true:v(t,l,m,w)?k=true:v(r,l,m,w)?k=true:v(l,p,t,r)?k=true:v(m,p,t,r)?k=true:v(w,p,t,r)?k=true:k=false}else if(g[5]){p=
[c[2]+m,c[3]+l];t=[c[4]+m,c[5]+l];r=[c[6]+m,c[7]+l];l=[g[2]+o,g[3]+n];m=[g[2]+o,g[5]+n];w=[g[4]+o,g[5]+n];n=[g[4]+o,g[3]+n];A(p,l,w)?k=true:A(t,l,w)?k=true:A(r,l,w)?k=true:v(l,p,t,r)?k=true:v(m,p,t,r)?k=true:v(w,p,t,r)?k=true:v(n,p,t,r)?k=true:k=false}else if(g[4]){p=[g[2]+o,g[3]+n,g[4]];t=[c[2]+m,c[3]+l];r=[c[4]+m,c[5]+l];n=[c[6]+m,c[7]+l];v([p[0],p[1]],t,r,n)?k=true:E(t,r,p)?k=true:E(r,n,p)?k=true:E(t,n,p)?k=true:k=false}else{p=[c[2]+m,c[3]+l];t=[c[4]+m,c[5]+l];r=[c[6]+m,c[7]+l];l=[g[2]+o,g[3]+
n];k=v(l,p,t,r)}else if(c[5])if(g[7]){p=[c[2]+m,c[3]+l];t=[c[2]+m,c[5]+l];r=[c[4]+m,c[5]+l];var ca=[c[4]+m,c[3]+l];l=[g[2]+o,g[3]+n];m=[g[4]+o,g[5]+n];w=[g[6]+o,g[7]+n];A(l,p,r)?k=true:A(m,p,r)?k=true:A(w,p,r)?k=true:v(p,l,m,w)?k=true:v(t,l,m,w)?k=true:v(r,l,m,w)?k=true:v(ca,l,m,w)?k=true:k=false}else if(g[5])if(m+c[4]<=o+g[2])k=false;else if(m+c[2]>=o+g[4])k=false;else if(l+c[5]<=n+g[3])k=false;else{if(l+c[3]>=n+g[5])k=false}else if(g[4]){k=g[2]+o;p=g[3]+n;t=g[4];r=c[2]+m;o=c[4]+m;m=c[3]+l;n=c[5]+
l;k=Z(k,p,t,r,m,o,n)}else k=A([g[2]+o,g[5]+n],[c[2]+m,c[3]+l],[c[4]+m,c[5]+l]);else if(c[4])if(g[7]){p=[c[2]+m,c[3]+l,c[4]];t=[g[2]+o,g[3]+n];r=[g[4]+o,g[5]+n];n=[g[6]+o,g[7]+n];v([p[0],p[1]],t,r,n)?k=true:E(t,r,p)?k=true:E(r,n,p)?k=true:E(t,n,p)?k=true:k=false}else if(g[5]){k=c[2]+m;p=c[3]+l;t=c[4];r=g[2]+o;o=g[4]+o;m=g[3]+n;n=g[5]+n;k=Z(k,p,t,r,m,o,n)}else if(g[4])k=ba(c[2]+m,c[3]+l,c[4],g[2]+o,g[3]+n,g[4]);if(k==true)j[j.length]=[[a,c[0]],[d,g[0]]]}}}q.O&&q.O()}if(j.length>0)for(a=0;a<j.length;a++){e.b[j[a][0][0]].z&&
e.b[j[a][0][0]].z(j[a][1][1],j[a][0][1],j[a][1][0])==false&&i.push(j[a][0][0]);e.b[j[a][1][0]].z&&e.b[j[a][1][0]].z(j[a][0][1],j[a][1][1],j[a][0][0])==false&&i.push(j[a][1][0])}if(i.length>0){i.sort(function(da,ea){return da-ea});i.reverse();s=[];a=0;a:for(;a<i.length;a++){for(d=0;d<s.length;d++)if(s[d]==i[a])continue a;s[s.length]=i[a]}for(a=0;a<s.length;a++)e.P(s[a])}a=0;for(d=e.c[2].length;a<d;a++)e.rules[e.c[2][a]].a.d&&e.rules[e.c[2][a]].v();for(a=0;a<e.b.length;a++){e.b[a].a.f+=e.b[a].a.j;e.b[a].a.e+=
e.b[a].a.k;e.b[a].a.p+=e.b[a].a.s;if(e.b[a].a.l){i=document.getElementById("ent_"+e.b[a].a.name);i.style.left=e.b[a].a.f+"px";i.style.top=e.b[a].a.e+"px";i.style.zIndex=e.b[a].a.p}e.b[a].a.V()}a=0;for(d=e.c[3].length;a<d;a++)e.rules[e.c[3][a]].a.d&&e.rules[e.c[3][a]].v();if(typeof L=="function"){L();L=null}b=new Date-b;if(H==true){B=b<C?setTimeout("rw.run()",C-b):setTimeout("rw.run()",1);S=b-C}else{clearTimeout(e.ja);R+=B;B=0}};this.Q()});window.rw=fa;
