var q=new (function(){var c=this,f=false,i=0,y=0;this.getTime=function(b){return b=="g"?i+y:i};var F=0,G=0,H=0;this.wa=function(){return G};this.xa=function(){return H};var D=50;this.Ta=function(b){D=1E3/parseInt(b);return c};this.Ha=function(){return 1E3/D};this.fa=function(){return F};var A="sprites/";this.Ua=function(b){A=b;return c};this.Ia=function(){return A};var O=false,Z=0,P=0;this.pa=function(b,a){O=true;Z=b;P=a;return c};this.Wa=function(){O=false;P=Z=0;return c};var L=false,J=[["bsp",8],
["tab",9],["ent",13],["shf",16],["ctr",17],["alt",18],["pau",19],["cap",20],["esc",27],["sp",32],["pgu",33],["pgd",34],["end",35],["hom",36],["la",37],["ua",38],["ra",39],["da",40],["ins",45],["del",46],["d0",48],["d1",49],["d2",50],["d3",51],["d4",52],["d5",53],["d6",54],["d7",55],["d8",56],["d9",57],["sem",59],["eql",61],["a",65],["b",66],["c",67],["d",68],["e",69],["f",70],["g",71],["h",72],["i",73],["j",74],["k",75],["l",76],["m",77],["n",78],["o",79],["p",80],["q",81],["r",82],["s",83],["t",
84],["u",85],["v",86],["w",67],["x",88],["y",89],["z",90],["lwn",91],["rwn",92],["sel",93],["n0",96],["n1",97],["n2",98],["n3",99],["n4",100],["n5",101],["n6",102],["n7",103],["n8",104],["n9",105],["mul",106],["add",107],["sub",109],["dec",110],["div",111],["f1",112],["f2",113],["f3",114],["f4",115],["f5",116],["f6",117],["f7",118],["f8",119],["f9",120],["f10",121],["f11",122],["f12",123],["num",144],["scr",145],["com",188],["per",190],["fsl",191],["acc",192],["obr",219],["bsl",220],["cbr",221],["qot",
222]];function $(b,a){for(var e=J.length,k=0;k<e;k++)if(J[k][1]==b)J[k][2]=a}function aa(b){$((b?b:window.event).keyCode,true);L=true}function ba(b){$((b?b:window.event).keyCode,false);L=true}this.key=function(b){for(var a=J.length,e=0;e<a;e++)if(J[e][0]==b)return J[e][2]?true:false};var V=0,W=0,M=false;this.A=new function(){this.x=function(){return V};this.y=function(){return W};this.da=function(){return M}};function da(b){if(!b)b=window.event;if(b.offsetX){V=b.offsetX;W=b.offsetY}else{V=b.layerX;
W=b.layerY}}M=function(){M=true};function ea(){M=false}function X(b,a,e){e=e*0.0174532925;b=[b[0]-a[0],b[1]-a[1]];b=[b[0]*Math.cos(e)-b[1]*Math.sin(e),b[0]*Math.sin(e)+b[1]*Math.cos(e)];b[0]+=a[0];b[1]+=a[1];return b}this.b=[];this.o=function(b,a,e,k,v,l){this.o="";this.name=b;this.C=a;this.F=e;this.B=k;this.width=v;this.height=l;this.s=this.c=this.d=0;this.Na=function(){return this.d};this.Oa=function(){return this.c};this.O=function(){return this.d+this.width};this.P=function(){return this.c+this.height};
this.w=this.j=this.f=0;this.u=this.g=false;this.display=function(g,d,j,h){this.F=g;this.d=d;this.c=j;this.s=h?h:j;this.g=true;if(g!==""){this.u=true;d=document.createElement("div");d.id="ent_"+this.name;d.style.width=this.width;d.style.height=this.height;if(g!=" "){d.style.backgroundImage="url('"+A+this.C+"/"+g+"."+this.B+"')";d.style.backgroundRepeat="no-repeat"}d.style.position="absolute";d.style.left=this.d+"px";d.style.top=this.c+"px";document.getElementById("board").appendChild(d);if(this.k.length>
0)for(g=0;g<this.k.length;g++)x(this,this.k[g])}else this.u=false;return this};this.z=function(){if(document.getElementById("ent_"+this.name)){var g=document.getElementById("ent_"+this.name);g.parentNode.removeChild(g)}this.u=this.g=false;return this};this.l=function(g){this.F=g;var d=document.getElementById("ent_"+this.name);if(d)if(g!=""){this.u=true;d.style.backgroundImage="url('"+A+this.C+"/"+g+"."+this.B+"')"}else{d.parentNode.removeChild(d);this.u=false}else if(g!="")this.display(g,this.d,this.c,
this.d);else this.u=false;return this};this.oa=function(g,d){var j=document.getElementById("ent_"+this.name);if(j)j.style.background="url('"+A+this.C+"/"+this.F+"."+this.B+"') "+g+"px "+d+"px no-repeat"};this.K={};this.za=function(g,d,j){this.K[g]=[d,j];return this};this.Va=function(g){g in this.K&&this.oa(this.K[g][0],this.K[g][1]);return this};this.move=function(g,d,j){this.f+=g;this.j+=d;this.w+=j?j:d;return this};this.Ea=function(){return[this.f,this.j,this.w]};this.ua=function(g){if(g)if(g==
"x")this.f=0;else if(g=="y")this.j=0;else{if(g=="z")this.w=0}else this.w=this.j=this.f=0;return this};this.moveTo=function(g,d,j){this.d=g;this.c=d;this.s=j||j==0?j:d;return this};this.rotate=function(g){var d=document.getElementById("ent_"+this.name);if(d)d.style[c.R.Y]="rotate("+g+"deg)";return this};this.Sa=function(g,d){var j=[this.width/2,this.height/2],h=[g[0],g[1]],p=X([g[2],g[3]],j,d),r=X([g[4],g[5]],j,d);j=X([g[6],g[7]],j,d);h.push(p[0]);h.push(p[1]);h.push(r[0]);h.push(r[1]);h.push(j[0]);
h.push(j[1]);return h};this.Ja=function(){return O?Math.floor(this.c/P):false};this.Ka=function(){return O?Math.floor(this.c/P):false};this.Da=function(){if(c.A.da())if(c.A.x()>this.d&&c.A.x()<this.O())if(c.A.y()>this.c&&c.A.y()<this.P())return true;return false};this.$=function(g){var d=document.getElementById("ent_"+this.name);d&&d.appendChild(g);return this};this.detach=function(){var g=document.getElementById("ent_"+this.name);if(g)for(var d=g.childNodes.length,j=0;j<d;j++)g.removeChild(g.childNodes[0]);
return this};this.k=[];this.ya=function(g,d,j,h,p,r,n,m,o){this.k.push([g,d,j,h,p,r,n,m?m:0,o?o:0]);document.getElementById("ent_"+this.name)&&x(this,this.k[this.k.length-1]);return this};function t(g,d){if(typeof d=="number")var j=g.k[d];else for(var h=0;h<g.k.length;h++)if(g.k[h][0]==d){j=g.k[h];break}if(j)return j;return false}function x(g,d){var j=document.getElementById("ent_"+g.name+"_"+d[0]);if(j){j.style.left=d[2]+"px";j.style.top=d[3]+"px";j.style.zIndex=d[4];j.style.width=d[5]+"px";j.style.height=
d[6]+"px";j.style.background='url("'+A+g.C+"/"+d[1]+"."+g.B+'") no-repeat '+d[7]+"px "+d[8]+"px"}else{var h=document.getElementById("ent_"+g.name);if(h){j=document.createElement("div");j.id="ent_"+g.name+"_"+d[0];j.style.position="absolute";j.style.left=d[2]+"px";j.style.top=d[3]+"px";j.style.zIndex=d[4];j.style.width=d[5]+"px";j.style.height=d[6]+"px";j.style.overflow="hidden";if(d[1]!=" ")j.style.background='url("'+A+g.C+"/"+d[1]+"."+g.B+'") no-repeat '+d[7]+"px "+d[8]+"px";h.appendChild(j)}}}this.Ma=
function(g,d,j,h){if(g=t(this,g)){g[2]=d;g[3]=j;g[4]=h;x(this,g)}return this};this.Qa=function(g,d,j){if(g=t(this,g)){g[5]=d;g[6]=j;x(this,g)}return this};this.Ca=function(g,d,j,h){if(g=t(this,g)){g[1]=d;g[7]=j||j===0?j:g[7];g[8]=h||h===0?h:g[8];x(this,g)}return this};this.removeChild=function(g){if(typeof g=="number")var d=g;else for(var j=0;j<this.k.length;j++)if(this.k[j][0]==g){d=j;break}if(d||d==0){g=document.getElementById("ent_"+this.name+"_"+this.k[d][0]);g.parentNode.removeChild(g);this.k.slice(d,
1)}return this};this.back=function(){return this.o};this.end=function(){return c}};this.h=function(b){b.a.ent=b;c.b[c.b.length]=b;b.N&&b.N();return b};this.la=function(b){c.b.splice(b,1);return c};this.m={};this.map=function(b,a,e,k,v){this.name=b;this.path=a;this.ea=e;this.g=false;this.width=k;this.height=v;this.y=this.x=0;this.D=-1;this.move=function(l,t,x){this.x+=l;this.y+=t;if(x)this.D+=x;if(document.getElementById("map_"+this.name)){l=document.getElementById("map_"+this.name);l.style.marginLeft=
this.x+"px";l.style.marginTop=this.y+"px";l.style.zIndex=this.D}return this};this.moveTo=function(l,t,x){this.x=l;this.y=t;if(x)this.D=x;if(document.getElementById("map_"+this.name)){l=document.getElementById("map_"+this.name);l.style.marginLeft=this.x+"px";l.style.marginTop=this.y+"px";l.style.zIndex=this.D}return this};this.display=function(){this.g=true;if(document.getElementById("map_"+this.name))document.getElementById("map_"+this.name).style.display="block";else{var l=document.createElement("div");
l.id="map_"+this.name;l.style.backgroundImage="url('"+A+"maps/"+this.path+"."+this.ea+"')";l.style.width=this.width+"px";l.style.height=this.height+"px";l.style.position="absolute";l.style.overflow="hidden";l.style.marginLeft=this.x+"px";l.style.marginTop=this.y+"px";l.style.zIndex=this.D;document.getElementById("board").appendChild(l)}return this};this.z=function(){this.g=false;if(document.getElementById("map_"+this.name))document.getElementById("map_"+this.name).style.display="none";return this};
this.remove=function(){this.g=false;if(document.getElementById("map_"+this.name)){var l=document.getElementById("map_"+this.name);l.parentNode.removeChild(l)}return this};this.end=function(){return c}};this.ha=function(b,a,e,k,v){c.m[b]=new c.map(b,a,e,k,v);return c.m[b]};this.Pa=function(b){c.m[b]&&delete c.m[b];return c};this.rules={};this.e=[[],[],[],[]];this.r=function(b,a){this.g=b;this.V=a};this.U=function(b,a){c.rules[b]=a;c.e[a.a.V].push(b);return c};this.removeRule=function(b){if(c.rules[b]){for(var a=
c.e[c.rules[b].a.V],e=0,k=a.length;e<k;e++)if(a[e]==b){a.splice(e,1);break}delete c.rules[b]}return c};var B={};function E(b){var a=b instanceof Array?[]:{};for(prop in b)a[prop]=prop=="ent"?"":b[prop]&&typeof b[prop]=="object"?E(b[prop],a):b[prop];return a}this.na=function(b){B[b]={};B[b].ents=E(c.b,c);B[b].maps=E(c.m,c);B[b].rules=E(c.rules,c);B[b].ruleList=E(c.e,c);for(var a=B[b].ents.length,e=0;e<a;e++)B[b].ents[e].a.ent=B[b].ents[e];return c};this.La=function(b){if(B[b])return true;return false};
this.ga=function(b){if(B[b]){c.b=E(B[b].ents,b);c.m=E(B[b].maps,b);c.rules=E(B[b].rules,b);c.e=E(B[b].ruleList,b);for(map in c.m)c.m[map].g==true&&c.m[map].display();b=c.b.length;for(var a=0;a<b;a++){c.b[a].a.o=c.b[a];c.b[a].a.g==true&&c.b[a].a.display(c.b[a].a.F,c.b[a].a.d,c.b[a].a.c,c.b[a].a.s)}L=true}return c};this.Ra=function(b){B[b]&&delete B[b];return c};var Q=null;this.Ba=function(b){Q=b;return c};var R=null;this.Aa=function(b){R=b;return c};this.Z=function(b,a){var e=new XMLHttpRequest;e.open("GET",
b,true);e.overrideMimeType("application/json");e.onreadystatechange=function(){if(e.readyState==4){eval("("+e.responseText+")");eval(a+"(resp)")}};e.send(null);return c};this.Ga=function(){return c};this.W={};this.t=[];this.ja=function(b){var a=c.t.length;c.t[a]=document.createElement("audio");c.t[a].src=c.W[b].src;c.t[a].play();return c};this.ia=function(b,a){c.W[b]=new Audio(a);return c};var S=[];this.M=function(b,a,e){for(var k=e.length,v=0;v<k;v++){S[S.length]=new Image;S[S.length-1].src=A+b+
"/"+e[v]+"."+a}return c};this.ba=function(b){document.getElementById("board").style.cursor="url('"+A+b+"')";return c};this.R={ca:function(){function b(){for(var a=document.getElementsByTagName("body")[0],e=["transform","WebkitTransform","MozTransform"],k;k=e.shift();)if(typeof a.style[k]!="undefined")return k;return false}this.Y=b()?b():"none"},Y:"none"};this.ra=function(){for(var b=document.getElementById("board"),a=b.childNodes.length,e=0;e<a;e++)b.removeChild(b.childNodes[0]);return c};this.sa=
function(){c.b=[];return c};this.ta=function(){c.m={};return c};this.va=function(){c.rules={};c.e=[[],[],[],[]];return c};this.qa=function(){c.ra().sa().ta().va();return c};this.N=function(b,a,e){c.R.ca();var k=document.createElement("div");k.id="board";G=b;H=a;k.style.width=b+"px";k.style.height=a+"px";k.style.overflow="hidden";k.style.position="relative";e?document.getElementById(e).appendChild(k):document.getElementsByTagName("body")[0].appendChild(k);if(window.document.addEventListener){window.document.addEventListener("keydown",
aa,false);window.document.addEventListener("keyup",ba,false)}else{window.document.attachEvent("onkeydown",aa);window.document.attachEvent("onkeyup",ba)}k.onmousemove=da;k.onmousedown=M;k.onmouseup=ea;return c};this.start=function(){if(f==false){f=true;i=setTimeout("rw.run()",D)}return c};this.stop=function(){f=false;return c};function Y(b,a,e,k){b=(e[0]-a[0])*(b[1]-a[1])-(e[1]-a[1])*(b[0]-a[0]);return(e[0]-a[0])*(k[1]-a[1])-(e[1]-a[1])*(k[0]-a[0])>=0?b>=0?true:false:b<=0?true:false}function z(b,a,
e,k){return Y(b,a,e,k)?Y(b,e,k,a)?Y(b,k,a,e)?true:false:false:false}function I(b,a,e){if(b[0]<a[0])return false;if(b[0]>e[0])return false;if(b[1]<a[1])return false;if(b[1]>e[1])return false;return true}function fa(b,a,e,k,v,l){var t=true;(b-k)*(b-k)+(a-v)*(a-v)<(e+l)*(e+l)?t=true:t=false;return t}function K(b,a,e){if(e[0]-e[2]>b[0]&&e[0]-e[2]>a[0])return false;else if(e[0]+e[2]<b[0]&&e[0]+e[2]<a[0])return false;else if(e[1]-e[2]>b[1]&&e[1]-e[2]>a[1])return false;else if(e[1]+e[2]<b[1]&&e[1]+e[2]<
a[1])return false;else{var k=b[0]*a[1]+a[0]*e[1]+e[0]*b[1]-a[0]*b[1]-e[0]*a[1]-b[0]*e[1];if(k<0)k=-k;return e[2]>k/Math.sqrt((a[0]-b[0])*(a[0]-b[0])+(a[1]-b[1])*(a[1]-b[1]))?true:false}}function ca(b,a,e,k,v,l,t){var x=true;l=(l-k)/2;b=b-(k+l);if(b<0)b=-b;if(b>l+e)x=false;else{t=(t-v)/2;a=a-(v+t);if(a<0)a=-a;x=a>t+e?false:b<=l?true:a<=t?true:(b+l)*(b+l)+(a+t)*(a+t)<=e*e?true:false}return x}this.ma=function(){for(var b=new Date,a=0;a<c.t.length;a++)if(c.t[a].ended){c.t.splice(a,1);a--}if(typeof Q==
"function"){Q();Q=null}a=0;for(var e=c.e[0].length;a<e;a++)c.rules[c.e[0][a]].a.g&&c.rules[c.e[0][a]].r();var k=[],v=c.b.length;if(L==true){for(a=0;a<v;a++){e=c.b[a];if(e.a.g==true){e.T&&e.T();e=e.update(e.a.d,e.a.O(),e.a.c,e.a.P());e==false&&k.push(a)}else if(e.I){e=e.I();e==false&&k.push(a)}}L=false}else for(a=0;a<v;a++){e=c.b[a];if(e.a.g==true){e=e.update(e.a.d,e.a.O(),e.a.c,e.a.P());e==false&&k.push(a)}else if(e.I){e=e.I();e==false&&k.push(a)}}a=0;for(e=c.e[1].length;a<e;a++)c.rules[c.e[1][a]].a.g&&
c.rules[c.e[1][a]].r();var l=[];for(a=0;a<v;a++){var t=c.b[a];if(t.a.g&&t.n)for(e=a+1;e<v;e++){var x=c.b[e];if(x.a.g&&x.n)for(var g=0;g<t.n.length;g++)for(var d=t.n[g],j=0;j<x.n.length;j++){var h=x.n[j],p=false,r=d[1];if(r)for(var n=r.length,m=0;m<n;m++)if(r[m]==h[0])p=true;if(p){var o=t.a.d+t.a.f;n=t.a.c+t.a.j;r=x.a.d+x.a.f;p=x.a.c+x.a.j;m=true;if(d[7])if(h[7]){var s=[d[2]+o,d[3]+n],w=[d[4]+o,d[5]+n],u=[d[6]+o,d[7]+n];n=[h[2]+r,h[3]+p];o=[h[4]+r,h[5]+p];var C=[h[6]+r,h[7]+p];z(s,n,o,C)?m=true:z(w,
n,o,C)?m=true:z(u,n,o,C)?m=true:z(n,s,w,u)?m=true:z(o,s,w,u)?m=true:z(C,s,w,u)?m=true:m=false}else if(h[5]){s=[d[2]+o,d[3]+n];w=[d[4]+o,d[5]+n];u=[d[6]+o,d[7]+n];n=[h[2]+r,h[3]+p];o=[h[2]+r,h[5]+p];C=[h[4]+r,h[5]+p];p=[h[4]+r,h[3]+p];I(s,n,C)?m=true:I(w,n,C)?m=true:I(u,n,C)?m=true:z(n,s,w,u)?m=true:z(o,s,w,u)?m=true:z(C,s,w,u)?m=true:z(p,s,w,u)?m=true:m=false}else if(h[4]){s=[h[2]+r,h[3]+p,h[4]];w=[d[2]+o,d[3]+n];u=[d[4]+o,d[5]+n];p=[d[6]+o,d[7]+n];z([s[0],s[1]],w,u,p)?m=true:K(w,u,s)?m=true:K(u,
p,s)?m=true:K(w,p,s)?m=true:m=false}else{s=[d[2]+o,d[3]+n];w=[d[4]+o,d[5]+n];u=[d[6]+o,d[7]+n];n=[h[2]+r,h[3]+p];m=z(n,s,w,u)}else if(d[5])if(h[7]){s=[d[2]+o,d[3]+n];w=[d[2]+o,d[5]+n];u=[d[4]+o,d[5]+n];var ga=[d[4]+o,d[3]+n];n=[h[2]+r,h[3]+p];o=[h[4]+r,h[5]+p];C=[h[6]+r,h[7]+p];I(n,s,u)?m=true:I(o,s,u)?m=true:I(C,s,u)?m=true:z(s,n,o,C)?m=true:z(w,n,o,C)?m=true:z(u,n,o,C)?m=true:z(ga,n,o,C)?m=true:m=false}else if(h[5])if(o+d[4]<=r+h[2])m=false;else if(o+d[2]>=r+h[4])m=false;else if(n+d[5]<=p+h[3])m=
false;else{if(n+d[3]>=p+h[5])m=false}else if(h[4]){m=h[2]+r;s=h[3]+p;w=h[4];u=d[2]+o;r=d[4]+o;o=d[3]+n;p=d[5]+n;m=ca(m,s,w,u,o,r,p)}else m=I([h[2]+r,h[5]+p],[d[2]+o,d[3]+n],[d[4]+o,d[5]+n]);else if(d[4])if(h[7]){s=[d[2]+o,d[3]+n,d[4]];w=[h[2]+r,h[3]+p];u=[h[4]+r,h[5]+p];p=[h[6]+r,h[7]+p];z([s[0],s[1]],w,u,p)?m=true:K(w,u,s)?m=true:K(u,p,s)?m=true:K(w,p,s)?m=true:m=false}else if(h[5]){m=d[2]+o;s=d[3]+n;w=d[4];u=h[2]+r;r=h[4]+r;o=h[3]+p;p=h[5]+p;m=ca(m,s,w,u,o,r,p)}else if(h[4])m=fa(d[2]+o,d[3]+n,d[4],
h[2]+r,h[3]+p,h[4]);if(m==true)l[l.length]=[[a,d[0]],[e,h[0]]]}}}t.ka&&t.ka()}if(l.length>0)for(a=0;a<l.length;a++){c.b[l[a][0][0]].v&&c.b[l[a][0][0]].v(l[a][1][1],l[a][0][1],l[a][1][0])==false&&k.push(l[a][0][0]);c.b[l[a][1][0]].v&&c.b[l[a][1][0]].v(l[a][0][1],l[a][1][1],l[a][0][0])==false&&k.push(l[a][1][0])}if(k.length>0){k.sort(function(ha,ia){return ha-ia});k.reverse();v=[];a=0;a:for(;a<k.length;a++){for(e=0;e<v.length;e++)if(v[e]==k[a])continue a;v[v.length]=k[a]}for(a=0;a<v.length;a++)c.la(v[a])}a=
0;for(e=c.e[2].length;a<e;a++)c.rules[c.e[2][a]].a.g&&c.rules[c.e[2][a]].r();for(a=0;a<c.b.length;a++){c.b[a].a.d+=c.b[a].a.f;c.b[a].a.c+=c.b[a].a.j;c.b[a].a.s+=c.b[a].a.w;if(c.b[a].a.u){k=document.getElementById("ent_"+c.b[a].a.name);k.style.left=c.b[a].a.d+"px";k.style.top=c.b[a].a.c+"px";k.style.zIndex=c.b[a].a.s}c.b[a].a.ua()}a=0;for(e=c.e[3].length;a<e;a++)c.rules[c.e[3][a]].a.g&&c.rules[c.e[3][a]].r();if(typeof R=="function"){R();R=null}b=new Date-b;if(f==true){i=b<D?setTimeout("rw.run()",D-
b):setTimeout("rw.run()",1);F=b-D}else{clearTimeout(c.Fa);y+=i;i=0}}});window.rw=q;window.rw.run=q.ma;window.rw.ents=q.b;window.rw.maps=q.m;window.rw.rules=q.rules;window.rw.ruleList=q.e;q.ia("boom","exp.ogg");function N(c,f,i,y){this.a=new q.o(c," "," "," ",i,y);this.n=[[f,["bman"],0,0,i,y]];this.update=function(){}}
function T(c){var f=this;f.a=new q.o(c,"blast","blast","gif",40,32);f.i=25;f.update=function(){f.a.s=f.a.c;f.i-=1;if(f.i<=0){f.a.z();return false}};f.n=[["blast",["bman","baddie","bomb"],0,0,40,32]]}
function ja(c,f){var i=this;i.a=new q.o(c,"bomb","1","gif",40,32);i.i=150;i.Q=2;i.update=function(){if(i.i==150){i.a.s=i.a.c;i.a.l("2")}else if(i.i==125)i.a.l("1");else if(i.i==100)i.a.l("2");else if(i.i==75)i.a.l("3");else if(i.i==50)i.a.l("2");else i.i==25&&i.a.l("3");i.i-=1;if(i.i<=0){q.ja("boom");var y=[i.a.d,i.a.c],F=[i.a.d,i.a.c],G=[i.a.d,i.a.c],H=[i.a.d,i.a.c];q.h(new T("blast"+q.b.length)).a.display("c",y[0],y[1],y[1]);for(var D=0;D<i.Q;D++){y[1]-=i.a.height;F[0]+=i.a.width;G[1]+=i.a.height;
H[0]-=i.a.width;var A="";if(D+1==i.Q)A="T";q.h(new T("blast"+q.b.length+"_"+i.a.name)).a.display("u"+A,y[0],y[1],y[1]).end().h(new T("blast"+q.b.length+"_"+i.a.name)).a.display("l"+A,F[0],F[1],F[1]).end().h(new T("blast"+q.b.length+"_"+i.a.name)).a.display("d"+A,G[0],G[1],G[1]).end().h(new T("blast"+q.b.length+"_"+i.a.name)).a.display("r"+A,H[0],H[1],H[1])}i.a.z();return false}};i.n=[[f,["blast"],0,0,40,32]];i.v=function(y){if(y=="blast")i.i=1}}
function U(c){var f=this;f.a=new q.o(c,"bman","l","gif",40,64);f.X=5;f.L=0;f.p="l";f.i=100;f.I=function(){f.i--;f.i<1&&f.a.display("Wr",200,100,132)};f.update=function(){if(f.p=="r")if(f.L<39){f.L++;f.a.f=f.X}else{f.a.f=0;f.p="l";f.a.l("Wl")}else if(f.L>0){f.L--;f.a.f=-f.X}else{f.a.f=0;f.p="r";f.a.l("Wr")}};f.n=[["baddie",["blast","bman"],0,0,40,64]];f.v=function(i){if(i=="blast"){f.a.z();return false}}}
q.M("bman","gif",["u","d","l","r","Wu","Wd","Wl","Wr"]).M("blast","gif",["c","u","d","l","r","uT","dT","lT","rT"]).M("bomb","gif",["1","2","3"]).M("maps","jpg",["map"]).N(600,600,"game").ba("blank.cur").pa(20,20).ha("map1","map","jpg",1200,600).display().end().U("rule1",new (function(){var c=this;c.a=new q.r(true,3);c.S=false;c.r=function(){c.S==true&&q.qa().ga("test")}})(true)).U("rule2",new (function(){var c=this;c.a=new q.r(true,2);c.H=0;c.forward=true;c.r=function(){if(c.forward==true)if(c.H>
-600){c.H--;q.m.map1.move(-1,0)}else c.forward=false;else if(c.H<0){c.H++;q.m.map1.move(1,0)}else c.forward=true}})).h(new U("baddie_1")).a.end().h(new U("baddie_2")).a.display("Wr",150,200,232).end().h(new U("baddie_3")).a.display("Wr",100,400,432).end().h(new U("baddie_4")).a.display("Wr",50,500,532).end().h(new (function(c){var f=this;f.a=new q.o(c,"bman","u","gif",40,64);f.J=5;f.G=5;f.aa=15;f.q=[];f.p="u";f.update=function(){f.a.f=0;f.a.j=0;if(f.G<5)f.G+=1;if(f.q.length>0)for(var i=0;i<f.q.length;i++)if(f.q[i]>
0)f.q[i]-=1;else f.q.splice(i,1);if(q.key("sp"))if(f.G==5)if(f.q.length<f.aa){f.G=0;f.q[f.q.length]=150;i=f.a.d;var y=f.a.c+32;q.h(new ja("bomb"+q.b.length)).a.display("1",i,y,y)}if(q.key("la"))f.a.f+=-f.J;if(q.key("ra"))f.a.f+=f.J;if(q.key("ua"))f.a.j+=-f.J;if(q.key("da"))f.a.j+=f.J;f.a.w=f.a.j};f.T=function(){document.getElementById("ent_"+c);if(q.key("la")){f.p="l";f.a.l("Wl")}else if(q.key("ua")){f.p="u";f.a.l("Wu")}else if(q.key("ra")){f.p="r";f.a.l("Wr")}else if(q.key("da")){f.p="d";f.a.l("Wd")}else f.a.l(f.p)};
f.n=[["bman",["blast","baddie","lWall","rWall","tWall","dWall"],0,0,40,64]];f.v=function(i){if(i=="blast"||i=="baddie"){q.rules.rule1.S=true;f.a.z();return false}if(i=="lWall")if(f.a.f>0)f.a.d+=-f.a.f;if(i=="tWall")if(f.a.j>0)f.a.c+=-f.a.j;if(i=="rWall")if(f.a.f<0)f.a.d+=-f.a.f;if(i=="dWall")if(f.a.j<0)f.a.c+=-f.a.j}})("Goon0","bman")).a.display("u",50,50,82).end().h(new N("tWall1","tWall",99,1)).a.display("blank",251,250,0).end().h(new N("rWall1","rWall",1,99)).a.display("blank",350,251,0).end().h(new N("lWall1",
"lWall",1,99)).a.display("blank",250,250,0).end().h(new N("dWall1","dWall",99,1)).a.display("blank",250,350,0).end().h(new (function(){var c=this;c.a=new q.o("lag","","","",150,20);c.update=function(){c.a.detach();c.a.$(document.createTextNode("Lag: "+q.fa()+"(ms)"))}})).a.display("blank",0,0,0).end().start().na("test").Z("ajaxtest.json","addGuy");
