var o=new (function(){var c=this,v=false,x=0,C=0;this.getTime=function(b){return b=="g"?x+C:x};var F=0,G=0,I=0;this.wa=function(){return G};this.xa=function(){return I};var B=50;this.Ta=function(b){B=1E3/parseInt(b);return c};this.Ha=function(){return 1E3/B};this.ga=function(){return F};var D="sprites/";this.Ua=function(b){D=b;return c};this.Ia=function(){return D};var O=false,Z=0,P=0;this.pa=function(b,a){O=true;Z=b;P=a;return c};this.Wa=function(){O=false;P=Z=0;return c};var L=false,J=[["bsp",8],
["tab",9],["ent",13],["shf",16],["ctr",17],["alt",18],["pau",19],["cap",20],["esc",27],["sp",32],["pgu",33],["pgd",34],["end",35],["hom",36],["la",37],["ua",38],["ra",39],["da",40],["ins",45],["del",46],["d0",48],["d1",49],["d2",50],["d3",51],["d4",52],["d5",53],["d6",54],["d7",55],["d8",56],["d9",57],["sem",59],["eql",61],["a",65],["b",66],["c",67],["d",68],["e",69],["f",70],["g",71],["h",72],["i",73],["j",74],["k",75],["l",76],["m",77],["n",78],["o",79],["p",80],["q",81],["r",82],["s",83],["t",
84],["u",85],["v",86],["w",67],["x",88],["y",89],["z",90],["lwn",91],["rwn",92],["sel",93],["n0",96],["n1",97],["n2",98],["n3",99],["n4",100],["n5",101],["n6",102],["n7",103],["n8",104],["n9",105],["mul",106],["add",107],["sub",109],["dec",110],["div",111],["f1",112],["f2",113],["f3",114],["f4",115],["f5",116],["f6",117],["f7",118],["f8",119],["f9",120],["f10",121],["f11",122],["f12",123],["num",144],["scr",145],["com",188],["per",190],["fsl",191],["acc",192],["obr",219],["bsl",220],["cbr",221],["qot",
222]];function $(b,a){for(var e=J.length,i=0;i<e;i++)if(J[i][1]==b)J[i][2]=a}function aa(b){$((b?b:window.event).keyCode,true);L=true}function ba(b){$((b?b:window.event).keyCode,false);L=true}this.key=function(b){for(var a=J.length,e=0;e<a;e++)if(J[e][0]==b)return J[e][2]?true:false};var V=0,W=0,M=false;this.A=new function(){this.x=function(){return V};this.y=function(){return W};this.ea=function(){return M}};function da(b){if(!b)b=window.event;if(b.offsetX){V=b.offsetX;W=b.offsetY}else{V=b.layerX;
W=b.layerY}}M=function(){M=true};function ea(){M=false}function X(b,a,e){e=e*0.0174532925;b=[b[0]-a[0],b[1]-a[1]];b=[b[0]*Math.cos(e)-b[1]*Math.sin(e),b[0]*Math.sin(e)+b[1]*Math.cos(e)];b[0]+=a[0];b[1]+=a[1];return b}this.b=[];this.n=function(b,a,e,i,t,j){this.n="";this.name=b;this.C=a;this.F=e;this.B=i;this.width=t;this.height=j;this.s=this.c=this.d=0;this.Na=function(){return this.d};this.Oa=function(){return this.c};this.O=function(){return this.d+this.width};this.P=function(){return this.c+this.height};
this.w=this.j=this.f=0;this.u=this.g=false;this.display=function(f,d,h,g){this.F=f;this.d=d;this.c=h;this.s=g?g:h;this.g=true;if(f!==""){this.u=true;d=document.createElement("div");d.id="ent_"+this.name;d.style.width=this.width;d.style.height=this.height;if(f!=" "){d.style.backgroundImage="url('"+D+this.C+"/"+f+"."+this.B+"')";d.style.backgroundRepeat="no-repeat"}d.style.position="absolute";d.style.left=this.d+"px";d.style.top=this.c+"px";document.getElementById("board").appendChild(d);if(this.k.length>
0)for(f=0;f<this.k.length;f++)w(this,this.k[f])}else this.u=false;return this};this.z=function(){if(document.getElementById("ent_"+this.name)){var f=document.getElementById("ent_"+this.name);f.parentNode.removeChild(f)}this.u=this.g=false;return this};this.l=function(f){this.F=f;var d=document.getElementById("ent_"+this.name);if(d)if(f!=""){this.u=true;d.style.backgroundImage="url('"+D+this.C+"/"+f+"."+this.B+"')"}else{d.parentNode.removeChild(d);this.u=false}else if(f!="")this.display(f,this.d,this.c,
this.d);else this.u=false;return this};this.oa=function(f,d){var h=document.getElementById("ent_"+this.name);if(h)h.style.background="url('"+D+this.C+"/"+this.F+"."+this.B+"') "+f+"px "+d+"px no-repeat"};this.K={};this.za=function(f,d,h){this.K[f]=[d,h];return this};this.Va=function(f){f in this.K&&this.oa(this.K[f][0],this.K[f][1]);return this};this.move=function(f,d,h){this.f+=f;this.j+=d;this.w+=h?h:d;return this};this.Ea=function(){return[this.f,this.j,this.w]};this.ua=function(f){if(f)if(f==
"x")this.f=0;else if(f=="y")this.j=0;else{if(f=="z")this.w=0}else this.w=this.j=this.f=0;return this};this.moveTo=function(f,d,h){this.d=f;this.c=d;this.s=h||h==0?h:d;return this};this.rotate=function(f){var d=document.getElementById("ent_"+this.name);if(d)d.style[c.R.Z]="rotate("+f+"deg)";return this};this.Sa=function(f,d){var h=[this.width/2,this.height/2],g=[f[0],f[1]],n=X([f[2],f[3]],h,d),p=X([f[4],f[5]],h,d);h=X([f[6],f[7]],h,d);g.push(n[0]);g.push(n[1]);g.push(p[0]);g.push(p[1]);g.push(h[0]);
g.push(h[1]);return g};this.Ja=function(){return O?Math.floor(this.c/P):false};this.Ka=function(){return O?Math.floor(this.c/P):false};this.Da=function(){if(c.A.ea())if(c.A.x()>this.d&&c.A.x()<this.O())if(c.A.y()>this.c&&c.A.y()<this.P())return true;return false};this.aa=function(f){var d=document.getElementById("ent_"+this.name);d&&d.appendChild(f);return this};this.detach=function(){var f=document.getElementById("ent_"+this.name);if(f)for(var d=f.childNodes.length,h=0;h<d;h++)f.removeChild(f.childNodes[0]);
return this};this.k=[];this.ya=function(f,d,h,g,n,p,l,k,m){this.k.push([f,d,h,g,n,p,l,k?k:0,m?m:0]);document.getElementById("ent_"+this.name)&&w(this,this.k[this.k.length-1]);return this};function r(f,d){if(typeof d=="number")var h=f.k[d];else for(var g=0;g<f.k.length;g++)if(f.k[g][0]==d){h=f.k[g];break}if(h)return h;return false}function w(f,d){var h=document.getElementById("ent_"+f.name+"_"+d[0]);if(h){h.style.left=d[2]+"px";h.style.top=d[3]+"px";h.style.zIndex=d[4];h.style.width=d[5]+"px";h.style.height=
d[6]+"px";h.style.background='url("'+D+f.C+"/"+d[1]+"."+f.B+'") no-repeat '+d[7]+"px "+d[8]+"px"}else{var g=document.getElementById("ent_"+f.name);if(g){h=document.createElement("div");h.id="ent_"+f.name+"_"+d[0];h.style.position="absolute";h.style.left=d[2]+"px";h.style.top=d[3]+"px";h.style.zIndex=d[4];h.style.width=d[5]+"px";h.style.height=d[6]+"px";h.style.overflow="hidden";if(d[1]!=" ")h.style.background='url("'+D+f.C+"/"+d[1]+"."+f.B+'") no-repeat '+d[7]+"px "+d[8]+"px";g.appendChild(h)}}}this.Ma=
function(f,d,h,g){if(f=r(this,f)){f[2]=d;f[3]=h;f[4]=g;w(this,f)}return this};this.Qa=function(f,d,h){if(f=r(this,f)){f[5]=d;f[6]=h;w(this,f)}return this};this.Ca=function(f,d,h,g){if(f=r(this,f)){f[1]=d;f[7]=h||h===0?h:f[7];f[8]=g||g===0?g:f[8];w(this,f)}return this};this.removeChild=function(f){if(typeof f=="number")var d=f;else for(var h=0;h<this.k.length;h++)if(this.k[h][0]==f){d=h;break}if(d||d==0){f=document.getElementById("ent_"+this.name+"_"+this.k[d][0]);f.parentNode.removeChild(f);this.k.slice(d,
1)}return this};this.back=function(){return this.n};this.end=function(){return c}};this.h=function(b){b.a.n=b;c.b[c.b.length]=b;b.N&&b.N();return b};this.la=function(b){c.b.splice(b,1);return c};this.m={};this.map=function(b,a,e,i,t){this.name=b;this.path=a;this.fa=e;this.g=false;this.width=i;this.height=t;this.y=this.x=0;this.D=-1;this.move=function(j,r,w){this.x+=j;this.y+=r;if(w)this.D+=w;if(document.getElementById("map_"+this.name)){j=document.getElementById("map_"+this.name);j.style.marginLeft=
this.x+"px";j.style.marginTop=this.y+"px";j.style.zIndex=this.D}return this};this.moveTo=function(j,r,w){this.x=j;this.y=r;if(w)this.D=w;if(document.getElementById("map_"+this.name)){j=document.getElementById("map_"+this.name);j.style.marginLeft=this.x+"px";j.style.marginTop=this.y+"px";j.style.zIndex=this.D}return this};this.display=function(){this.g=true;if(document.getElementById("map_"+this.name))document.getElementById("map_"+this.name).style.display="block";else{var j=document.createElement("div");
j.id="map_"+this.name;j.style.backgroundImage="url('"+D+"maps/"+this.path+"."+this.fa+"')";j.style.width=this.width+"px";j.style.height=this.height+"px";j.style.position="absolute";j.style.overflow="hidden";j.style.marginLeft=this.x+"px";j.style.marginTop=this.y+"px";j.style.zIndex=this.D;document.getElementById("board").appendChild(j)}return this};this.z=function(){this.g=false;if(document.getElementById("map_"+this.name))document.getElementById("map_"+this.name).style.display="none";return this};
this.remove=function(){this.g=false;if(document.getElementById("map_"+this.name)){var j=document.getElementById("map_"+this.name);j.parentNode.removeChild(j)}return this};this.end=function(){return c}};this.ha=function(b,a,e,i,t){c.m[b]=new c.map(b,a,e,i,t);return c.m[b]};this.Pa=function(b){c.m[b]&&delete c.m[b];return c};this.rules={};this.e=[[],[],[],[]];this.r=function(b,a){this.g=b;this.W=a};this.V=function(b,a){c.rules[b]=a;c.e[a.a.W].push(b);return c};this.removeRule=function(b){if(c.rules[b]){for(var a=
c.e[c.rules[b].a.W],e=0,i=a.length;e<i;e++)if(a[e]==b){a.splice(e,1);break}delete c.rules[b]}return c};var z={};function E(b){var a=b instanceof Array?[]:{};for(prop in b)a[prop]=prop=="ent"?"":b[prop]&&typeof b[prop]=="object"?E(b[prop],a):b[prop];return a}this.na=function(b){z[b]={};z[b].ents=E(c.b,c);z[b].maps=E(c.m,c);z[b].rules=E(c.rules,c);z[b].ruleList=E(c.e,c);for(var a=z[b].b.length,e=0;e<a;e++)z[b].ents[e].a.n=z[b].b[e];return c};this.La=function(b){if(z[b])return true;return false};this.U=
function(b){if(z[b]){c.b=E(z[b].b,b);c.m=E(z[b].m,b);c.rules=E(z[b].rules,b);c.e=E(z[b].e,b);for(map in c.m)c.m[map].g==true&&c.m[map].display();b=c.b.length;for(var a=0;a<b;a++){c.b[a].a.n=c.b[a];c.b[a].a.g==true&&c.b[a].a.display(c.b[a].a.F,c.b[a].a.d,c.b[a].a.c,c.b[a].a.s)}L=true}return c};this.Ra=function(b){z[b]&&delete z[b];return c};var Q=null;this.Ba=function(b){Q=b;return c};var R=null;this.Aa=function(b){R=b;return c};this.$=function(b,a){var e=new XMLHttpRequest;e.open("GET",b,true);e.overrideMimeType("application/json");
e.onreadystatechange=function(){if(e.readyState==4){eval("("+e.responseText+")");eval(a+"(resp)")}};e.send(null);return c};this.Ga=function(){return c};this.X={};this.t=[];this.ja=function(b){var a=c.t.length;c.t[a]=document.createElement("audio");c.t[a].src=c.X[b].src;c.t[a].play();return c};this.ia=function(b,a){c.X[b]=new Audio(a);return c};var S=[];this.M=function(b,a,e){for(var i=e.length,t=0;t<i;t++){S[S.length]=new Image;S[S.length-1].src=D+b+"/"+e[t]+"."+a}return c};this.ca=function(b){document.getElementById("board").style.cursor=
"url('"+D+b+"')";return c};this.R={da:function(){function b(){for(var a=document.getElementsByTagName("body")[0],e=["transform","WebkitTransform","MozTransform"],i;i=e.shift();)if(typeof a.style[i]!="undefined")return i;return false}this.Z=b()?b():"none"},Z:"none"};this.ra=function(){for(var b=document.getElementById("board"),a=b.childNodes.length,e=0;e<a;e++)b.removeChild(b.childNodes[0]);return c};this.sa=function(){c.b=[];return c};this.ta=function(){c.m={};return c};this.va=function(){c.rules=
{};c.e=[[],[],[],[]];return c};this.qa=function(){c.ra().sa().ta().va();return c};this.N=function(b,a,e){c.R.da();var i=document.createElement("div");i.id="board";G=b;I=a;i.style.width=b+"px";i.style.height=a+"px";i.style.overflow="hidden";i.style.position="relative";e?document.getElementById(e).appendChild(i):document.getElementsByTagName("body")[0].appendChild(i);if(window.document.addEventListener){window.document.addEventListener("keydown",aa,false);window.document.addEventListener("keyup",ba,
false)}else{window.document.attachEvent("onkeydown",aa);window.document.attachEvent("onkeyup",ba)}i.onmousemove=da;i.onmousedown=M;i.onmouseup=ea;return c};this.start=function(){if(v==false){v=true;x=setTimeout("rw.run()",B)}return c};this.stop=function(){v=false;return c};function Y(b,a,e,i){b=(e[0]-a[0])*(b[1]-a[1])-(e[1]-a[1])*(b[0]-a[0]);return(e[0]-a[0])*(i[1]-a[1])-(e[1]-a[1])*(i[0]-a[0])>=0?b>=0?true:false:b<=0?true:false}function y(b,a,e,i){return Y(b,a,e,i)?Y(b,e,i,a)?Y(b,i,a,e)?true:false:
false:false}function H(b,a,e){if(b[0]<a[0])return false;if(b[0]>e[0])return false;if(b[1]<a[1])return false;if(b[1]>e[1])return false;return true}function fa(b,a,e,i,t,j){var r=true;(b-i)*(b-i)+(a-t)*(a-t)<(e+j)*(e+j)?r=true:r=false;return r}function K(b,a,e){if(e[0]-e[2]>b[0]&&e[0]-e[2]>a[0])return false;else if(e[0]+e[2]<b[0]&&e[0]+e[2]<a[0])return false;else if(e[1]-e[2]>b[1]&&e[1]-e[2]>a[1])return false;else if(e[1]+e[2]<b[1]&&e[1]+e[2]<a[1])return false;else{var i=b[0]*a[1]+a[0]*e[1]+e[0]*b[1]-
a[0]*b[1]-e[0]*a[1]-b[0]*e[1];if(i<0)i=-i;return e[2]>i/Math.sqrt((a[0]-b[0])*(a[0]-b[0])+(a[1]-b[1])*(a[1]-b[1]))?true:false}}function ca(b,a,e,i,t,j,r){var w=true;j=(j-i)/2;b=b-(i+j);if(b<0)b=-b;if(b>j+e)w=false;else{r=(r-t)/2;a=a-(t+r);if(a<0)a=-a;w=a>r+e?false:b<=j?true:a<=r?true:(b+j)*(b+j)+(a+r)*(a+r)<=e*e?true:false}return w}this.ma=function(){for(var b=new Date,a=0;a<c.t.length;a++)if(c.t[a].ended){c.t.splice(a,1);a--}if(typeof Q=="function"){Q();Q=null}a=0;for(var e=c.e[0].length;a<e;a++)c.rules[c.e[0][a]].a.g&&
c.rules[c.e[0][a]].r();var i=[],t=c.b.length;if(L==true){for(a=0;a<t;a++){e=c.b[a];if(e.a.g==true){e.T&&e.T();e=e.update(e.a.d,e.a.O(),e.a.c,e.a.P());e==false&&i.push(a)}else if(e.I){e=e.I();e==false&&i.push(a)}}L=false}else for(a=0;a<t;a++){e=c.b[a];if(e.a.g==true){e=e.update(e.a.d,e.a.O(),e.a.c,e.a.P());e==false&&i.push(a)}else if(e.I){e=e.I();e==false&&i.push(a)}}a=0;for(e=c.e[1].length;a<e;a++)c.rules[c.e[1][a]].a.g&&c.rules[c.e[1][a]].r();var j=[];for(a=0;a<t;a++){var r=c.b[a];if(r.a.g&&r.o)for(e=
a+1;e<t;e++){var w=c.b[e];if(w.a.g&&w.o)for(var f=0;f<r.o.length;f++)for(var d=r.o[f],h=0;h<w.o.length;h++){var g=w.o[h],n=false,p=d[1];if(p)for(var l=p.length,k=0;k<l;k++)if(p[k]==g[0])n=true;if(n){var m=r.a.d+r.a.f;l=r.a.c+r.a.j;p=w.a.d+w.a.f;n=w.a.c+w.a.j;k=true;if(d[7])if(g[7]){var q=[d[2]+m,d[3]+l],u=[d[4]+m,d[5]+l],s=[d[6]+m,d[7]+l];l=[g[2]+p,g[3]+n];m=[g[4]+p,g[5]+n];var A=[g[6]+p,g[7]+n];y(q,l,m,A)?k=true:y(u,l,m,A)?k=true:y(s,l,m,A)?k=true:y(l,q,u,s)?k=true:y(m,q,u,s)?k=true:y(A,q,u,s)?k=
true:k=false}else if(g[5]){q=[d[2]+m,d[3]+l];u=[d[4]+m,d[5]+l];s=[d[6]+m,d[7]+l];l=[g[2]+p,g[3]+n];m=[g[2]+p,g[5]+n];A=[g[4]+p,g[5]+n];n=[g[4]+p,g[3]+n];H(q,l,A)?k=true:H(u,l,A)?k=true:H(s,l,A)?k=true:y(l,q,u,s)?k=true:y(m,q,u,s)?k=true:y(A,q,u,s)?k=true:y(n,q,u,s)?k=true:k=false}else if(g[4]){q=[g[2]+p,g[3]+n,g[4]];u=[d[2]+m,d[3]+l];s=[d[4]+m,d[5]+l];n=[d[6]+m,d[7]+l];y([q[0],q[1]],u,s,n)?k=true:K(u,s,q)?k=true:K(s,n,q)?k=true:K(u,n,q)?k=true:k=false}else{q=[d[2]+m,d[3]+l];u=[d[4]+m,d[5]+l];s=[d[6]+
m,d[7]+l];l=[g[2]+p,g[3]+n];k=y(l,q,u,s)}else if(d[5])if(g[7]){q=[d[2]+m,d[3]+l];u=[d[2]+m,d[5]+l];s=[d[4]+m,d[5]+l];var ga=[d[4]+m,d[3]+l];l=[g[2]+p,g[3]+n];m=[g[4]+p,g[5]+n];A=[g[6]+p,g[7]+n];H(l,q,s)?k=true:H(m,q,s)?k=true:H(A,q,s)?k=true:y(q,l,m,A)?k=true:y(u,l,m,A)?k=true:y(s,l,m,A)?k=true:y(ga,l,m,A)?k=true:k=false}else if(g[5])if(m+d[4]<=p+g[2])k=false;else if(m+d[2]>=p+g[4])k=false;else if(l+d[5]<=n+g[3])k=false;else{if(l+d[3]>=n+g[5])k=false}else if(g[4]){k=g[2]+p;q=g[3]+n;u=g[4];s=d[2]+
m;p=d[4]+m;m=d[3]+l;n=d[5]+l;k=ca(k,q,u,s,m,p,n)}else k=H([g[2]+p,g[5]+n],[d[2]+m,d[3]+l],[d[4]+m,d[5]+l]);else if(d[4])if(g[7]){q=[d[2]+m,d[3]+l,d[4]];u=[g[2]+p,g[3]+n];s=[g[4]+p,g[5]+n];n=[g[6]+p,g[7]+n];y([q[0],q[1]],u,s,n)?k=true:K(u,s,q)?k=true:K(s,n,q)?k=true:K(u,n,q)?k=true:k=false}else if(g[5]){k=d[2]+m;q=d[3]+l;u=d[4];s=g[2]+p;p=g[4]+p;m=g[3]+n;n=g[5]+n;k=ca(k,q,u,s,m,p,n)}else if(g[4])k=fa(d[2]+m,d[3]+l,d[4],g[2]+p,g[3]+n,g[4]);if(k==true)j[j.length]=[[a,d[0]],[e,g[0]]]}}}r.ka&&r.ka()}if(j.length>
0)for(a=0;a<j.length;a++){c.b[j[a][0][0]].v&&c.b[j[a][0][0]].v(j[a][1][1],j[a][0][1],j[a][1][0])==false&&i.push(j[a][0][0]);c.b[j[a][1][0]].v&&c.b[j[a][1][0]].v(j[a][0][1],j[a][1][1],j[a][0][0])==false&&i.push(j[a][1][0])}if(i.length>0){i.sort(function(ha,ia){return ha-ia});i.reverse();t=[];a=0;a:for(;a<i.length;a++){for(e=0;e<t.length;e++)if(t[e]==i[a])continue a;t[t.length]=i[a]}for(a=0;a<t.length;a++)c.la(t[a])}a=0;for(e=c.e[2].length;a<e;a++)c.rules[c.e[2][a]].a.g&&c.rules[c.e[2][a]].r();for(a=
0;a<c.b.length;a++){c.b[a].a.d+=c.b[a].a.f;c.b[a].a.c+=c.b[a].a.j;c.b[a].a.s+=c.b[a].a.w;if(c.b[a].a.u){i=document.getElementById("ent_"+c.b[a].a.name);i.style.left=c.b[a].a.d+"px";i.style.top=c.b[a].a.c+"px";i.style.zIndex=c.b[a].a.s}c.b[a].a.ua()}a=0;for(e=c.e[3].length;a<e;a++)c.rules[c.e[3][a]].a.g&&c.rules[c.e[3][a]].r();if(typeof R=="function"){R();R=null}b=new Date-b;if(v==true){x=b<B?setTimeout("rw.run()",B-b):setTimeout("rw.run()",1);F=b-B}else{clearTimeout(c.Fa);C+=x;x=0}}});window.rw=o;
window.rw.run=o.ma;window.rw.loadState=o.U;o.ia("boom","exp.ogg");function ja(){this.a=new o.n("lag","","","",150,20);this.update=function(){this.a.detach();this.a.aa(document.createTextNode("Lag: "+o.ga()+"(ms)"))}}function N(c,v,x,C){this.a=new o.n(c," "," "," ",x,C);this.o=[[v,["bman"],0,0,x,C]];this.update=function(){}}
function T(c){this.a=new o.n(c,"blast","blast","gif",40,32);this.i=25;this.update=function(){this.a.s=this.a.c;this.i-=1;if(this.i<=0){this.a.z();return false}};this.o=[["blast",["bman","baddie","bomb"],0,0,40,32]]}
function ka(c,v){this.a=new o.n(c,"bomb","1","gif",40,32);this.i=150;this.Q=2;this.update=function(){if(this.i==150){this.a.s=this.a.c;this.a.l("2")}else if(this.i==125)this.a.l("1");else if(this.i==100)this.a.l("2");else if(this.i==75)this.a.l("3");else if(this.i==50)this.a.l("2");else this.i==25&&this.a.l("3");this.i-=1;if(this.i<=0){o.ja("boom");var x=[this.a.d,this.a.c],C=[this.a.d,this.a.c],F=[this.a.d,this.a.c],G=[this.a.d,this.a.c];o.h(new T("blast"+o.b.length)).a.display("c",x[0],x[1],x[1]);
for(var I=0;I<this.Q;I++){x[1]-=this.a.height;C[0]+=this.a.width;F[1]+=this.a.height;G[0]-=this.a.width;var B="";if(I+1==this.Q)B="T";o.h(new T("blast"+o.b.length+"_"+this.a.name)).a.display("u"+B,x[0],x[1],x[1]).end().h(new T("blast"+o.b.length+"_"+this.a.name)).a.display("l"+B,C[0],C[1],C[1]).end().h(new T("blast"+o.b.length+"_"+this.a.name)).a.display("d"+B,F[0],F[1],F[1]).end().h(new T("blast"+o.b.length+"_"+this.a.name)).a.display("r"+B,G[0],G[1],G[1])}this.a.z();return false}};this.o=[[v,["blast"],
0,0,40,32]];this.v=function(x){if(x=="blast")this.i=1}}
function U(c){this.a=new o.n(c,"bman","l","gif",40,64);this.Y=5;this.L=0;this.p="l";this.i=100;this.I=function(){this.i--;this.i<1&&this.a.display("Wr",200,100,132)};this.update=function(){if(this.p=="r")if(this.L<39){this.L++;this.a.f=this.Y}else{this.a.f=0;this.p="l";this.a.l("Wl")}else if(this.L>0){this.L--;this.a.f=-this.Y}else{this.a.f=0;this.p="r";this.a.l("Wr")}};this.o=[["baddie",["blast","bman"],0,0,40,64]];this.v=function(v){if(v=="blast"){this.a.z();return false}}}
function la(c){this.a=new o.n(c,"bman","u","gif",40,64);this.G=this.J=5;this.ba=15;this.q=[];this.p="u";this.update=function(){this.a.f=0;this.a.j=0;if(this.G<5)this.G+=1;if(this.q.length>0)for(var v=0;v<this.q.length;v++)if(this.q[v]>0)this.q[v]-=1;else this.q.splice(v,1);if(o.key("sp"))if(this.G==5)if(this.q.length<this.ba){this.G=0;this.q[this.q.length]=150;v=this.a.d;var x=this.a.c+32;o.h(new ka("bomb"+o.b.length)).a.display("1",v,x,x)}if(o.key("la"))this.a.f+=-this.J;if(o.key("ra"))this.a.f+=
this.J;if(o.key("ua"))this.a.j+=-this.J;if(o.key("da"))this.a.j+=this.J;this.a.w=this.a.j};this.T=function(){document.getElementById("ent_"+c);if(o.key("la")){this.p="l";this.a.l("Wl")}else if(o.key("ua")){this.p="u";this.a.l("Wu")}else if(o.key("ra")){this.p="r";this.a.l("Wr")}else if(o.key("da")){this.p="d";this.a.l("Wd")}else this.a.l(this.p)};this.o=[["bman",["blast","baddie","lWall","rWall","tWall","dWall"],0,0,40,64]];this.v=function(v){if(v=="blast"||v=="baddie"){o.rules.rule1.S=true;this.a.z();
return false}if(v=="lWall")if(this.a.f>0)this.a.d+=-this.a.f;if(v=="tWall")if(this.a.j>0)this.a.c+=-this.a.j;if(v=="rWall")if(this.a.f<0)this.a.d+=-this.a.f;if(v=="dWall")if(this.a.j<0)this.a.c+=-this.a.j}}function ma(){this.a=new o.r(true,3);this.S=false;this.r=function(){this.S==true&&o.qa().U("test")}}
function na(){this.a=new o.r(true,2);this.H=0;this.forward=true;this.r=function(){if(this.forward==true)if(this.H>-600){this.H--;o.m.map1.move(-1,0)}else this.forward=false;else if(this.H<0){this.H++;o.m.map1.move(1,0)}else this.forward=true}}
window.startGame=function(){o.M("bman","gif",["u","d","l","r","Wu","Wd","Wl","Wr"]).M("blast","gif",["c","u","d","l","r","uT","dT","lT","rT"]).M("bomb","gif",["1","2","3"]).M("maps","jpg",["map"]).N(600,600,"game").ca("blank.cur").pa(20,20).ha("map1","map","jpg",1200,600).display().end().V("rule1",new ma(true)).V("rule2",new na).h(new U("baddie_1")).a.end().h(new U("baddie_2")).a.display("Wr",150,200,232).end().h(new U("baddie_3")).a.display("Wr",100,400,432).end().h(new U("baddie_4")).a.display("Wr",
50,500,532).end().h(new la("Goon0","bman")).a.display("u",50,50,82).end().h(new N("tWall1","tWall",99,1)).a.display("blank",251,250,0).end().h(new N("rWall1","rWall",1,99)).a.display("blank",350,251,0).end().h(new N("lWall1","lWall",1,99)).a.display("blank",250,250,0).end().h(new N("dWall1","dWall",99,1)).a.display("blank",250,350,0).end().h(new ja).a.display("blank",0,0,0).end().start().na("test").$("ajaxtest.json","addGuy")};
